plugins {
    kotlin("jvm") version "2.4.20"
    kotlin("plugin.serialization") version "2.4.20"
    id("io.ktor.plugin") version "3.6.0"
}

group = "bayern.kickner"
version = "1.0.0"

repositories {
    mavenCentral()
    maven {
        name = "nexus421MavenReleases"
        url = uri("https://maven.kickner.bayern/releases")
    }
}

dependencies {
    // Klogger 0.3.0 is also the SLF4J provider, so Ktor's own log output ends up in Klogger as well
    implementation("bayern.kickner:Klogger:0.3.0")
    implementation("bayern.kickner:KotNexLib:4.4.1")

    implementation("io.ktor:ktor-server-core")
    implementation("io.ktor:ktor-server-cio")
    implementation("io.ktor:ktor-server-sessions")
    implementation("io.ktor:ktor-server-html-builder")
    implementation("io.ktor:ktor-server-default-headers")
    implementation("io.ktor:ktor-server-body-limit")
    implementation("io.ktor:ktor-client-core")
    implementation("io.ktor:ktor-client-cio")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
    implementation("org.jetbrains.exposed:exposed-core:1.5.0")
    implementation("org.jetbrains.exposed:exposed-jdbc:1.5.0")
    implementation("org.xerial:sqlite-jdbc:3.53.4.0")

    testImplementation(kotlin("test"))
    testImplementation("io.ktor:ktor-server-test-host")
}

kotlin {
    // The vendor is pinned as well, so toolchain resolution cannot substitute another distribution
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
        vendor.set(JvmVendorSpec.AMAZON)
    }
}

application {
    mainClass.set("bayern.kickner.kshort.MainKt")
}

ktor {
    fatJar {
        archiveFileName.set("kshort.jar")
    }
}

/**
 * Writes `BuildConfig.kt` with the version from this script and the time of the build. The file lives under
 * `build/` and is therefore not versioned. The timestamp is taken when the task runs, so the task is never
 * up to date and the file is rewritten on every build.
 */
abstract class GenerateBuildConfig : DefaultTask() {
    @get:Input
    abstract val version: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    init {
        outputs.upToDateWhen { false }
    }

    @TaskAction
    fun generate() {
        val file = outputDir.get().file("bayern/kickner/kshort/BuildConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package bayern.kickner.kshort
            |
            |/** Generated by Gradle on every build (see build.gradle.kts). Do not edit, do not commit. */
            |object BuildConfig {
            |    /** The `version` from build.gradle.kts. */
            |    const val VERSION = "${version.get()}"
            |
            |    /** Time of the build as Unix timestamp in milliseconds. */
            |    const val BUILD_TIME = ${System.currentTimeMillis()}L
            |}
            |""".trimMargin()
        )
    }
}

val generateBuildConfig by tasks.registering(GenerateBuildConfig::class) {
    version.set(project.version.toString())
    outputDir.set(layout.buildDirectory.dir("generated/buildConfig/kotlin"))
}

// Registering the task as source directory makes compileKotlin (and with it test) depend on it
kotlin.sourceSets.main {
    kotlin.srcDir(generateBuildConfig)
}

tasks.test {
    useJUnitPlatform()
}
